### ISSUE TITLE
Github desktop error after I deleted a file

### ISSUE THREAD

**Issue by Johaning** [Watts-College/cpp-528-template#1] opened 2022-04-19 23:53 UTC
I did what I now realize was a dumb move and hopefully have not broken everything permanently! 
Working locally in my branch on the lab, I saved my lab .Rmd file that had all my code working through the tutorial, and then renamed and saved-as to delete out the unneeded tutorial code to submit. Both version were saved in my local folder, and then I saved the version with unneeded code into a different folder and deleted it from the project lab folder. 

Now github desktop is giving me an error that says "fatal: missing object 417d68e3e56ae5edaf7484caa3aa9275b2094afb for refs/heads/main." I tried saving the deleted file back into the folder, but anything I do in github desktop just generates that same error message. I was able to commit my branch. 

How should I handle this? I'd still like to get rid of that unneeded .Rmd file, but also to make sure things work and not have github desktop shouting "Fatal" at me. And for future reference, is there a way that I could have saved that unneeded version of my file without causing this mess? 
Thank you for any help!!

**Comment by yukicruz** [comment] 2022-04-20 05:14
Duplicate of #1208979803 : https://github.com/Watts-College/cpp-528-spr-2022/issues/15#issue-1208979803

**Closed as completed** 2023-03-01 19:36 UTC
